version: '3.8'

services:
  trading-bot:
    build: .
    container_name: binance-trading-bot
    restart: unless-stopped
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./db:/app/db
      - ./reports:/app/reports
      - ./config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - trading-network

  # Optional: PostgreSQL database (uncomment if using PostgreSQL)
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: trading-bot-db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: trading_bot
  #     POSTGRES_USER: trader
  #     POSTGRES_PASSWORD: your_secure_password
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - trading-network
  #   ports:
  #     - "5432:5432"

networks:
  trading-network:
    driver: bridge

# Uncomment if using PostgreSQL
# volumes:
#   postgres-data: